// ═══════════════════════════════════════════
//  SINDHI KEY DATA (from branah.com/sindhi)
// ═══════════════════════════════════════════

export const KEYS_SINDHI = [
  /* k0  ` */ { n:"\u2018", s:"\u2019", latin:'`',  caps:false },
  /* k1  1 */ { n:'۱',     s:'!',      latin:'1',  caps:false },
  /* k2  2 */ { n:'۲',     s:'ى',      latin:'2',  caps:false },
  /* k3  3 */ { n:'۳',     s:'ؔ',      latin:'3',  caps:false },
  /* k4  4 */ { n:'۴',     s:'ؒ',      latin:'4',  caps:false },
  /* k5  5 */ { n:'۵',     s:'٪',      latin:'5',  caps:false },
  /* k6  6 */ { n:'٦',     s:'ؓ',      latin:'6',  caps:false },
  /* k7  7 */ { n:'۷',     s:'۽',      latin:'7',  caps:false },
  /* k8  8 */ { n:'۸',     s:'ؤ',      latin:'8',  caps:false },
  /* k9  9 */ { n:'۹',     s:')',      latin:'9',  caps:false },
  /* k10 0 */ { n:'۰',     s:'(',      latin:'0',  caps:false },
  /* k11 - */ { n:'ڏ',     s:'_',      latin:'-',  caps:false },
  /* k12 = */ { n:'ڌ',     s:'+',      latin:'=',  caps:false },
  /* k13 q */ { n:'ق',     s:'َ',      latin:'q',  caps:true  },
  /* k14 w */ { n:'ص',     s:'ض',      latin:'w',  caps:true  },
  /* k15 e */ { n:'ي',     s:'ِ',      latin:'e',  caps:true  },
  /* k16 r */ { n:'ر',     s:'ڙ',      latin:'r',  caps:true  },
  /* k17 t */ { n:'ت',     s:'ٽ',      latin:'t',  caps:true  },
  /* k18 y */ { n:'ٿ',     s:'ث',      latin:'y',  caps:true  },
  /* k19 u */ { n:'ع',     s:'غ',      latin:'u',  caps:true  },
  /* k20 i */ { n:'ڳ',     s:'ھ',      latin:'i',  caps:true  },
  /* k21 o */ { n:'و',     s:'ُ',      latin:'o',  caps:false },
  /* k22 p */ { n:'پ',     s:'ڦ',      latin:'p',  caps:true  },
  /* k23 [ */ { n:'ڇ',     s:'ڃ',      latin:'[',  caps:false },
  /* k24 ] */ { n:'چ',     s:'ڄ',      latin:']',  caps:false },
  /* k25 \\ */ { n:'ڍ',     s:'ٺ',      latin:'\\', caps:false },
  /* k26 a */ { n:'ا',     s:'آ',      latin:'a',  caps:true  },
  /* k27 s */ { n:'س',     s:'ش',      latin:'s',  caps:true  },
  /* k28 d */ { n:'د',     s:'ڊ',      latin:'d',  caps:true  },
  /* k29 f */ { n:'ف',     s:'ڦ',      latin:'f',  caps:true  },
  /* k30 g */ { n:'گ',     s:'ً',      latin:'g',  caps:true  },
  /* k31 h */ { n:'ه',     s:'ح',      latin:'h',  caps:true  },
  /* k32 j */ { n:'ج',     s:'ٍ',      latin:'j',  caps:true  },
  /* k33 k */ { n:'ڪ',     s:'\u06E1', latin:'k',  caps:true  },
  /* k34 l */ { n:'ل',     s:':',      latin:'l',  caps:true  },
  /* k35 ; */ { n:'ک',     s:'؛',      latin:';',  caps:false },
  /* k36 ' */ { n:'ڱ',     s:'"',      latin:"'",  caps:false },
  /* k37 z */ { n:'ز',     s:'ذ',      latin:'z',  caps:true  },
  /* k38 x */ { n:'خ',     s:'ّ',      latin:'x',  caps:true  },
  /* k39 c */ { n:'ط',     s:'ظ',      latin:'c',  caps:true  },
  /* k40 v */ { n:'ڀ',     s:'ء',      latin:'v',  caps:true  },
  /* k41 b */ { n:'ب',     s:'ٻ',      latin:'b',  caps:true  },
  /* k42 n */ { n:'ن',     s:'ڻ',      latin:'n',  caps:true  },
  /* k43 m */ { n:'م',     s:'۾',      latin:'m',  caps:false },
  /* k44 , */ { n:'،',     s:'\u201C', latin:',',  caps:false },
  /* k45 . */ { n:'.',     s:'\u201D', latin:'.',  caps:false },
  /* k46 / */ { n:'ئ',     s:'؟',      latin:'/',  caps:false },
  /* k47 \\ */ { n:'÷',     s:'×',      latin:'\\', caps:false }
];
