// ═══════════════════════════════════════════
//  URDU KEY DATA (from branah.com/urdu)
// ═══════════════════════════════════════════

export const KEYS_STANDARD = [
  /* k0  ` */ { n:'`',         s:'~',         latin:'`'   },
  /* k1  1 */ { n:'1',         s:'!',         latin:'1'   },
  /* k2  2 */ { n:'2',         s:'@',         latin:'2'   },
  /* k3  3 */ { n:'3',         s:'#',         latin:'3'   },
  /* k4  4 */ { n:'4',         s:'$',         latin:'4'   },
  /* k5  5 */ { n:'5',         s:'٪',         latin:'5'   },
  /* k6  6 */ { n:'6',         s:'^',         latin:'6'   },
  /* k7  7 */ { n:'7',         s:'ۖ',         latin:'7'   },
  /* k8  8 */ { n:'8',         s:'٭',         latin:'8'   },
  /* k9  9 */ { n:'9',         s:')',         latin:'9'   },
  /* k10 0 */ { n:'0',         s:'(',         latin:'0'   },
  /* k11 - */ { n:'-',         s:'_',         latin:'-'   },
  /* k12 = */ { n:'=',         s:'+',         latin:'='   },
  /* k13 q */ { n:'ط',         s:'ظ',         latin:'q'   },
  /* k14 w */ { n:'ص',         s:'ض',         latin:'w'   },
  /* k15 e */ { n:'ھ',         s:'ذ',         latin:'e'   },
  /* k16 r */ { n:'د',         s:'ڈ',         latin:'r'   },
  /* k17 t */ { n:'ٹ',         s:'ث',         latin:'t'   },
  /* k18 y */ { n:'پ',         s:'ّ',         latin:'y'   },
  /* k19 u */ { n:'ت',         s:'ۃ',         latin:'u'   },
  /* k20 i */ { n:'ب',         s:'ـ',         latin:'i'   },
  /* k21 o */ { n:'ج',         s:'چ',         latin:'o'   },
  /* k22 p */ { n:'ح',         s:'خ',         latin:'p'   },
  /* k23 [ */ { n:']',         s:'}',         latin:'['   },
  /* k24 ] */ { n:'[',         s:'{',         latin:']'   },
  /* k25 \\ */ { n:'\\',        s:'|',         latin:'\\'  },
  /* k26 a */ { n:'م',         s:'ژ',         latin:'a'   },
  /* k27 s */ { n:'و',         s:'ز',         latin:'s'   },
  /* k28 d */ { n:'ر',         s:'ڑ',         latin:'d'   },
  /* k29 f */ { n:'ن',         s:'ں',         latin:'f'   },
  /* k30 g */ { n:'ل',         s:'ۂ',         latin:'g'   },
  /* k31 h */ { n:'ہ',         s:'ء',         latin:'h'   },
  /* k32 j */ { n:'ا',         s:'آ',         latin:'j'   },
  /* k33 k */ { n:'ک',         s:'گ',         latin:'k'   },
  /* k34 l */ { n:'ی',         s:'ي',         latin:'l'   },
  /* k35 ; */ { n:'؛',         s:':',         latin:';'   },
  /* k36 ' */ { n:'\u2018',    s:'\u201D',    latin:"'"   },
  /* k37 z */ { n:'ق',         s:'\u200D',    latin:'z'   },
  /* k38 x */ { n:'ف',         s:'\u200C',    latin:'x'   },
  /* k39 c */ { n:'ے',         s:'ۓ',         latin:'c'   },
  /* k40 v */ { n:'س',         s:'',          latin:'v'   },
  /* k41 b */ { n:'ش',         s:'ؤ',         latin:'b'   },
  /* k42 n */ { n:'غ',         s:'ئ',         latin:'n'   },
  /* k43 m */ { n:'ع',         s:'',          latin:'m'   },
  /* k44 , */ { n:'،',         s:'>',         latin:','   },
  /* k45 . */ { n:'۔',         s:'<',         latin:'.'   },
  /* k46 / */ { n:'/',         s:'؟',         latin:'/'   },
  /* k47 \\ */ { n:'\\',        s:'|',         latin:'\\'  }
];

export const KEYS_PHONETIC = [
  /* k0  ` */ { n:'؏',         s:'؎',         latin:'`',   caps:false },
  /* k1  1 */ { n:'۱',         s:'!',         latin:'1',   caps:false },
  /* k2  2 */ { n:'۲',         s:'@',         latin:'2',   caps:false },
  /* k3  3 */ { n:'۳',         s:'ؔ',         latin:'3',   caps:false },
  /* k4  4 */ { n:'۴',         s:'ؒ',         latin:'4',   caps:false },
  /* k5  5 */ { n:'۵',         s:'٪',         latin:'5',   caps:false },
  /* k6  6 */ { n:'٦',         s:'ؓ',         latin:'6',   caps:false },
  /* k7  7 */ { n:'۷',         s:'ؑ',         latin:'7',   caps:false },
  /* k8  8 */ { n:'۸',         s:'ؐ',         latin:'8',   caps:false },
  /* k9  9 */ { n:'۹',         s:')',         latin:'9',   caps:false },
  /* k10 0 */ { n:'۰',         s:'(',         latin:'0',   caps:false },
  /* k11 - */ { n:'-',         s:'',          latin:'-',   caps:false },
  /* k12 = */ { n:'=',         s:'+',         latin:'=',   caps:false },
  /* k13 q */ { n:'ق',         s:'ْ',         latin:'q',   caps:true  },
  /* k14 w */ { n:'و',         s:'ٔ',         latin:'w',   caps:true  },
  /* k15 e */ { n:'ع',         s:'ٰ',         latin:'e',   caps:true  },
  /* k16 r */ { n:'ر',         s:'ڑ',         latin:'r',   caps:true  },
  /* k17 t */ { n:'ت',         s:'ٹ',         latin:'t',   caps:true  },
  /* k18 y */ { n:'ے',         s:'َ',         latin:'y',   caps:true  },
  /* k19 u */ { n:'ء',         s:'ئ',         latin:'u',   caps:true  },
  /* k20 i */ { n:'ی',         s:'ِ',         latin:'i',   caps:true  },
  /* k21 o */ { n:'ہ',         s:'ۃ',         latin:'o',   caps:true  },
  /* k22 p */ { n:'پ',         s:'ُ',         latin:'p',   caps:true  },
  /* k23 [ */ { n:'﷽',         s:'ﷺ',         latin:'[',   caps:false },
  /* k24 ] */ { n:'ﷲ',         s:'ﷻ',         latin:']',   caps:false },
  /* k25 \\ */ { n:'÷',         s:'x',         latin:'\\',  caps:false },
  /* k26 a */ { n:'ا',         s:'آ',         latin:'a',   caps:true  },
  /* k27 s */ { n:'س',         s:'ص',         latin:'s',   caps:true  },
  /* k28 d */ { n:'د',         s:'ڈ',         latin:'d',   caps:true  },
  /* k29 f */ { n:'ف',         s:'أ',         latin:'f',   caps:true  },
  /* k30 g */ { n:'گ',         s:'غ',         latin:'g',   caps:true  },
  /* k31 h */ { n:'ح',         s:'ھ',         latin:'h',   caps:true  },
  /* k32 j */ { n:'ج',         s:'ض',         latin:'j',   caps:true  },
  /* k33 k */ { n:'ک',         s:'خ',         latin:'k',   caps:true  },
  /* k34 l */ { n:'ل',         s:'ٖ',         latin:'l',   caps:true  },
  /* k35 ; */ { n:'؛',         s:':',         latin:';',   caps:false },
  /* k36 ' */ { n:'',          s:'',          latin:"'",   caps:false },
  /* k37 z */ { n:'ز',         s:'ذ',         latin:'z',   caps:true  },
  /* k38 x */ { n:'ش',         s:'ژ',         latin:'x',   caps:true  },
  /* k39 c */ { n:'چ',         s:'ث',         latin:'c',   caps:true  },
  /* k40 v */ { n:'ط',         s:'ظ',         latin:'v',   caps:true  },
  /* k41 b */ { n:'ب',         s:'ً',         latin:'b',   caps:true  },
  /* k42 n */ { n:'ن',         s:'ں',         latin:'n',   caps:true  },
  /* k43 m */ { n:'م',         s:'ّ',         latin:'m',   caps:true  },
  /* k44 , */ { n:'،',         s:'ٗ',         latin:',',   caps:false },
  /* k45 . */ { n:'۔',         s:'.',         latin:'.',   caps:false },
  /* k46 / */ { n:'/',         s:'؟',         latin:'/',   caps:false },
  /* k47 \\ */ { n:'÷',         s:'x',         latin:'\\',  caps:false }
];
